# Travis CI (MIT License) configuration file for the FoundationPress WordPress theme.
# @link https://travis-ci.org/
#
# For use with the FoundationPress WordPress theme.
# @link https://github.com/olefredrik/foundationpress

# Declare project language.
# @link http://about.travis-ci.org/docs/user/languages/php/
language: php

branches:
  only:
    - master

# Declare versions of PHP to use. Use one decimal max.
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

# Declare which versions of WordPress to test against.
# Also declare whether or not to test in Multisite.
env:
  # Trunk
  # @link https://github.com/WordPress/WordPress
  - WP_VERSION=master WP_MULTISITE=0
  - WP_VERSION=master WP_MULTISITE=1
  # WordPress 4.6
  # @link https://github.com/WordPress/WordPress/tree/4.6-branch
  - WP_VERSION=4.6 WP_MULTISITE=0
  - WP_VERSION=4.6 WP_MULTISITE=1
  # WordPress 4.5
  # @link https://github.com/WordPress/WordPress/tree/4.5-branch
  - WP_VERSION=4.5 WP_MULTISITE=0
  - WP_VERSION=4.5 WP_MULTISITE=1
  # WordPress 4.4
  # @link https://github.com/WordPress/WordPress/tree/4.4-branch
  - WP_VERSION=4.4 WP_MULTISITE=0
  - WP_VERSION=4.4 WP_MULTISITE=1

# Declare 5.6 beta in test matrix.
# @link https://buddypress.trac.wordpress.org/ticket/5620
# @link http://docs.travis-ci.com/user/build-configuration/
matrix:
  include:
    - php: 5.6
      env: WP_VERSION=master
  allow_failures:
    - php: 5.6
  fast_finish: true

# Use this to prepare your build for testing.
# e.g. copy database configurations, environment variables, etc.
# Failures in this section will result in build status 'errored'.
before_script:
  # Set up WordPress installation.
  - export WP_DEVELOP_DIR=/tmp/wordpress/
  - mkdir -p $WP_DEVELOP_DIR
  # Use the Git mirror of WordPress.
  - git clone --depth=1 --branch="$WP_VERSION" git://develop.git.wordpress.org/ $WP_DEVELOP_DIR
  # Set up Twenty Sixteen theme information.
  - theme_slug=$(basename $(pwd))
  - export WP_THEME_DIR=$WP_DEVELOP_DIR/src/wp-content/themes/$theme_slug
  - cd ..
  - mv $theme_slug $WP_THEME_DIR
  # Set up WordPress configuration.
  - cd $WP_DEVELOP_DIR
  - echo $WP_DEVELOP_DIR
  - cp wp-tests-config-sample.php wp-tests-config.php
  - sed -i "s/youremptytestdbnamehere/wordpress_test/" wp-tests-config.php
  - sed -i "s/yourusernamehere/root/" wp-tests-config.php
  - sed -i "s/yourpasswordhere//" wp-tests-config.php
  # Create WordPress database.
  - mysql -e 'CREATE DATABASE wordpress_test;' -uroot
  # Install CodeSniffer for WordPress Coding Standards checks.
  - mkdir php-codesniffer && curl -L https://github.com/squizlabs/PHP_CodeSniffer/archive/master.tar.gz | tar xz --strip-components=1 -C php-codesniffer
  # Install WordPress Coding Standards.
  - mkdir wordpress-coding-standards && curl -L https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/archive/master.tar.gz | tar xz --strip-components=1 -C wordpress-coding-standards
  # Hop into CodeSniffer directory.
  - cd php-codesniffer
  # Set install path for WordPress Coding Standards
  # @link https://github.com/squizlabs/PHP_CodeSniffer/blob/4237c2fc98cc838730b76ee9cee316f99286a2a7/CodeSniffer.php#L1941
  - scripts/phpcs --config-set installed_paths ../wordpress-coding-standards
  # Hop into WordPress directory.
  - cd $WP_DEVELOP_DIR
  - cd ..
  # Install PHPMD
  - export PHPMD_DIR=$(pwd)/phpmd/
  - export PHPMD=${PHPMD_DIR}phpmd
  - mkdir -p ${PHPMD_DIR}
  - curl -L http://static.phpmd.org/php/latest/phpmd.phar -o ${PHPMD}
  - chmod +x ${PHPMD}
  # Hop into themes directory.
  - cd ${WP_THEME_DIR}
  # After CodeSniffer install you should refresh your path.
  - phpenv rehash

# Run test script commands.
# Default is specific to project language.
# All commands must exit with code 0 on success. Anything else is considered failure.
script:
  # Search for PHP syntax errors.
  - find . \( -name '*.php' \) -exec php -lf {} \;
  # WordPress Coding Standards
  # @link https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards
  # @link http://pear.php.net/package/PHP_CodeSniffer/
  # -p flag: Show progress of the run.
  # -s flag: Show sniff codes in all reports.
  # -v flag: Print verbose output.
  # -n flag: Do not print warnings. (shortcut for --warning-severity=0)
  # --standard: Use WordPress as the standard.
  # --extensions: Only sniff PHP files.
  - $WP_DEVELOP_DIR/php-codesniffer/scripts/phpcs -p -s -v -n . --standard=./codesniffer.ruleset.xml --extensions=php
  - ${PHPMD} ${WP_THEME_DIR}/ text ./phpmd.ruleset.xml

# Receive notifications for build results.
# @link http://docs.travis-ci.com/user/notifications/#Email-notifications
notifications:
  email: false
